In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Datasets/weatherAUS.csv")


In [3]:
dataset.head(6)

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   
5  2008-12-06   Albury     14.6     29.7       0.2          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   
5         WNW           56.0          W  ...        55.0         23.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   
5       1009.2       1005.4       NaN       NaN     20.6     28.9         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  
5            No  

[6 rows x 23 columns]

In [4]:
X = dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
Y = dataset.iloc[:,-1].values

In [5]:
# selected_columns = [
#     1, 2, 3, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21
# ]

# X = dataset.iloc[:, selected_columns].values

In [6]:
# selected_columns = slice(1, 5) + slice(7, 22)  # Define slices for the selected columns

# X = dataset.iloc[:, selected_columns].values

In [7]:
X

array([['Albury', 13.4, 22.9, ..., 16.9, 21.8, 'No'],
       ['Albury', 7.4, 25.1, ..., 17.2, 24.3, 'No'],
       ['Albury', 12.9, 25.7, ..., 21.0, 23.2, 'No'],
       ...,
       ['Uluru', 5.4, 26.9, ..., 12.5, 26.1, 'No'],
       ['Uluru', 7.8, 27.0, ..., 15.1, 26.0, 'No'],
       ['Uluru', 14.9, nan, ..., 15.0, 20.9, 'No']], dtype=object)

In [8]:
Y

array(['No', 'No', 'No', ..., 'No', 'No', nan], dtype=object)

In [9]:
# if you use slicing then you get 2D Y
# Y = dataset.iloc[:,21].values

In [10]:
# To reshape Y
Y = Y.reshape(-1,1)

In [11]:
Y

array([['No'],
       ['No'],
       ['No'],
       ...,
       ['No'],
       ['No'],
       [nan]], dtype=object)

# Dealing with Invalid Dataset 

In [12]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="most_frequent")

In [13]:
X = imputer.fit_transform(X)
Y = imputer.fit_transform(Y)

In [14]:
X

array([['Albury', 13.4, 22.9, ..., 16.9, 21.8, 'No'],
       ['Albury', 7.4, 25.1, ..., 17.2, 24.3, 'No'],
       ['Albury', 12.9, 25.7, ..., 21.0, 23.2, 'No'],
       ...,
       ['Uluru', 5.4, 26.9, ..., 12.5, 26.1, 'No'],
       ['Uluru', 7.8, 27.0, ..., 15.1, 26.0, 'No'],
       ['Uluru', 14.9, 20.0, ..., 15.0, 20.9, 'No']], dtype=object)

In [15]:
Y

array([['No'],
       ['No'],
       ['No'],
       ...,
       ['No'],
       ['No'],
       ['No']], dtype=object)

In [16]:
Y = Y.ravel()

In [17]:
Y.shape

(145460,)

In [18]:
Y

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

# Encoding Dataset

In [19]:
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])

le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4])

le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])

le4 = LabelEncoder()
X[:,7] = le4.fit_transform(X[:,7])

le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])

le6 = LabelEncoder()
Y = le6.fit_transform(Y)



In [20]:
X

array([[2, 13.4, 22.9, ..., 16.9, 21.8, 0],
       [2, 7.4, 25.1, ..., 17.2, 24.3, 0],
       [2, 12.9, 25.7, ..., 21.0, 23.2, 0],
       ...,
       [41, 5.4, 26.9, ..., 12.5, 26.1, 0],
       [41, 7.8, 27.0, ..., 15.1, 26.0, 0],
       [41, 14.9, 20.0, ..., 15.0, 20.9, 0]], dtype=object)

In [21]:
Y

array([0, 0, 0, ..., 0, 0, 0])

# Feature Scaling 

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [23]:
print(X)

[[-1.53166617  0.19132753 -0.04135977 ... -0.01407077  0.02310362
  -0.52979545]
 [-1.53166617 -0.75105231  0.26874452 ...  0.03244663  0.387799
  -0.52979545]
 [-1.53166617  0.11279588  0.35331842 ...  0.62166712  0.22733303
  -0.52979545]
 ...
 [ 1.20928479 -1.06517892  0.52246622 ... -0.69632607  0.65037966
  -0.52979545]
 [ 1.20928479 -0.68822699  0.53656187 ... -0.29317521  0.63579185
  -0.52979545]
 [ 1.20928479  0.42692249 -0.45013361 ... -0.30868102 -0.10818671
  -0.52979545]]


# Splitting dataset into training and testing 

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [25]:
print(X_train)

[[ 0.22535368  1.03946939  0.07140543 ...  0.68369032  0.08145488
  -0.52979545]
 [ 1.42012717 -0.45263203  0.11369237 ... -0.41722163  0.22733303
  -0.52979545]
 [ 0.50647685 -0.20133073 -0.14002932 ... -0.06058818 -0.02065982
   1.88752093]
 ...
 [ 1.0687232   0.75675544  0.93124006 ...  1.10234698  1.07342629
  -0.52979545]
 [ 0.57675765 -0.04426743 -0.16822062 ...  0.01694083 -0.28324049
   1.88752093]
 [ 1.63096955 -0.0285611  -0.91529006 ... -0.35519842 -0.76463838
  -0.52979545]]


In [26]:
print(Y_train)

[1 0 0 ... 0 0 0]


In [27]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=150,random_state=0)
classifier.fit(X_train,Y_train)
 

RandomForestClassifier(n_estimators=150, random_state=0)

In [28]:
classifier.score(X_train,Y_train)

0.9999398460057748

In [29]:
y_pred = classifier.predict(X_test)

In [30]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [31]:
y_pred = le6.inverse_transform(y_pred)

In [32]:
print(y_pred)

['No' 'No' 'No' ... 'No' 'No' 'No']


In [33]:
print(Y_test)

[1 1 0 ... 1 0 0]


In [34]:
Y_test = le6.inverse_transform(Y_test)

In [35]:
Y_test = Y_test.reshape(-1,1)
y_pred = y_pred.reshape(-1,1)


In [36]:
df = np.concatenate((Y_test,y_pred),axis=1)
# axis = 0 means horizontal concatenation 
# axis = 1 means vertical concatenation 

dataframe = pd.DataFrame(df,columns=['Rain on Tommorow','Prediction of Rain'])


In [37]:
print(df)

[['Yes' 'No']
 ['Yes' 'No']
 ['No' 'No']
 ...
 ['Yes' 'No']
 ['No' 'No']
 ['No' 'No']]


In [38]:
print(dataframe)

      Rain on Tommorow Prediction of Rain
0                  Yes                 No
1                  Yes                 No
2                   No                 No
3                   No                Yes
4                   No                 No
...                ...                ...
29087               No                Yes
29088               No                 No
29089              Yes                 No
29090               No                 No
29091               No                 No

[29092 rows x 2 columns]


In [39]:
dataframe.to_csv('prediction.csv')

# Calculating Accuracy

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8538086071772308

In [41]:
newdata = pd.read_csv("prediction.csv")

In [43]:
newdata.head(20)

Unnamed: 0 Rain on Tommorow Prediction of Rain
0            0              Yes                 No
1            1              Yes                 No
2            2               No                 No
3            3               No                Yes
4            4               No                 No
5            5               No                 No
6            6               No                 No
7            7              Yes                 No
8            8              Yes                Yes
9            9               No                 No
10          10               No                 No
11          11               No                 No
12          12              Yes                 No
13          13               No                 No
14          14               No                 No
15          15              Yes                 No
16          16               No                 No
17          17              Yes                 No
18          18               No                 No
19          19              Yes                 No